---
- name: Deploy Cash Out Gaming application
  hosts: all
  become: yes

  tasks:
  - name: Install dependencies
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - nodejs
      - npm

  - name: Clone repository
    git:
      repo: https://github.com/cash-out-gaming/cash-out-gaming.git
      dest: /var/www/cash-out-gaming

  - name: Install npm dependencies
    npm:
      path: /var/www/cash-out