from . import test_factories
from . import test_forms
from . import test_models
from . import test_services
from . import test_static
from . import test_templates
from . import test_urls
from . import test_utils
from . import test_views