version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/database

  db:
    image: postgres
    mongodb_compatible: true
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-data:/data/db
  prometheus:
    build: ./monitoring/prometheus
    ports:
      - "9090:9090"

  grafana:
    build: ./monitoring/grafana
    ports:
      - "3001:3001"

volumes:
  db-data: